### ISSUE TITLE
Fix broken live gmail test

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4594]
It seems like this PR broke live gmail test.
https://flowcrypt.semaphoreci.com/jobs/866f120d-0c1d-4cda-ac01-c61325804d2d

_Originally posted by @ioanmo226 in https://github.com/FlowCrypt/flowcrypt-browser/issues/4563#issuecomment-1209617849_

**Comment by rrrooommmaaa** [comment]
Fixed by #4595, thanks for noticing.

**Comment by ioanmo226** [comment]
You are welcome.
Hmm... I can see that live test still fails though

**Comment by rrrooommmaaa** [comment]
Are the live tests on `master` ok now? I'm having some troubles searching them, perhaps missing some privileges...

**Comment by ioanmo226** [comment]
I don't think so.
Live test sometimes fails on master.
Ex: https://flowcrypt.semaphoreci.com/workflows/dbf0f8d0-ea66-400a-acff-f05a6e906bee?pipeline_id=8637312d-0fac-4db0-b246-9809f12466c1

**Comment by ioanmo226** [comment]
Whole live tests are now broken. Maybe because of gmail behavior change.
Need to investigate and fix

**Comment by tomholub** [comment]
@ioanmo226 do you think you may be able to fix this, after the OOB PR?

**Comment by ioanmo226** [comment]
OK

**Comment by tomholub** [comment]
We could maybe go through each test and consider if it could be written as a mocked tests. Some of the tests that don't rely on Gmail HTML explicitly could be moved to mock.

For example there is a live test to check the initial notification user gets when they first install the extension, in Gmail it says "please go through setup" on top with a link to do it or dismiss or don't show again. That test could be moved to mocked tests now that we also have a mock of the Gmail page available. There may be a few more tests like that, which don't use nearly a single HTML tag from the Gmail webpage, and are therefore safe to mock instead. You could look into that in another issue, or if exactly it's such a test that is giving you trouble now, you could look into that in this issue.

**Comment by ioanmo226** [comment]
@tomholub `https://flowcrypt.com/api/account/login` api returns this error for this request.
I think something needs to be fixed in backend side?
```js
account: "ci.tests.gmail@flowcrypt.dev"
token: null
uuid: "c021c7d1eb1be867fb225797bb630ea0838882d6"
```

> "Wrong id_token: Unknown audience 717284730244-5oejn54f10gnrektjdc4fv4rbic1bj1p.apps.googleusercontent.com for issuer https://accounts.google.com"

**Comment by ioanmo226** [comment]
Please check this one too

**Comment by tomholub** [comment]
@ioanmo226 I have fixed the above issue, I believe, by updating the configuration on the server. But live tests are still failing. Could you please take a look if it's the same thing or something new?

**Comment by ioanmo226** [comment]
OK

**Comment by tomholub** [comment]
After this and #4594 I'll be able to do a release. I have bad experience doing releases until all tests are fixed. Thanks!
